# Generated by Django 6.1 on 2026-10-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('idea', 'Идея'), ('bug', 'Ошибка'), ('question', 'Вопрос')], default='idea', max_length=16, verbose_name='тип')),
                ('text', models.TextField(max_length=2000, verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Готово')], default='new', max_length=16, verbose_name='статус')),
                ('reply', models.TextField(blank=True, max_length=2000, verbose_name='ответ')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='ответ дан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='feedback_user_idx')],
            },
        ),
    ]
