# Generated by Django 6.1 on 2026-10-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_reply'),
        ('workouts', '0067_announce_feedback_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='заметка администратора'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='changelog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workouts.changelogentry', verbose_name='новость'),
        ),
    ]
