# Generated by Django 6.1 on 2026-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rest_seconds_default',
            field=models.PositiveSmallIntegerField(default=90, help_text='Используется, если у тренировки не задан свой отдых.', verbose_name='отдых между подходами, сек'),
        ),
    ]
