# Generated by Django 6.1 on 2026-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_rest_seconds_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changelog_seen_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — пользователь ещё не открывал «Что нового».', null=True, verbose_name='новости просмотрены'),
        ),
    ]
