# Generated by Django 6.1 on 2026-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_changelog_seen_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_goal_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сколько минут в неделю тренироваться. Пусто — цель не задана.', null=True, verbose_name='цель на неделю, мин'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_goal_minutes__isnull', True), models.Q(('weekly_goal_minutes__gte', 30), ('weekly_goal_minutes__lte', 2400)), _connector='OR'), name='weekly_goal_in_range'),
        ),
    ]
