# Generated by Django 6.1 on 2026-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_weekly_goal'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — аккаунт живёт. Иначе он отключён и через 30 дней удалится насовсем; вход до этого срока его возвращает (accounts.deletion).', null=True, verbose_name='удаление запрошено'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('deletion_requested_at__isnull', True), ('is_active', False), _connector='OR'), name='pending_deletion_is_inactive'),
        ),
    ]
