# Generated by Django 6.1 on 2026-08-27 14:15

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('muscle_group', models.CharField(blank=True, max_length=60, verbose_name='группа мышц')),
                ('owner', models.ForeignKey(blank=True, help_text='Пусто — глобальная запись, видна всем пользователям.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('category', models.CharField(choices=[('strength', 'Силовая'), ('cardio', 'Кардио')], max_length=10, verbose_name='категория')),
                ('owner', models.ForeignKey(blank=True, help_text='Пусто — глобальная запись, видна всем пользователям.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'вид спорта',
                'verbose_name_plural': 'виды спорта',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='начало')),
                ('duration_min', models.PositiveIntegerField(verbose_name='длительность, мин')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, help_text='Пусто — берётся значение по умолчанию из профиля.', null=True, verbose_name='отдых между подходами, сек')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='workouts.sport', verbose_name='вид спорта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StrengthSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='номер подхода')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='вес, кг')),
                ('reps', models.PositiveSmallIntegerField(verbose_name='повторения')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='workouts.exercise', verbose_name='упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workout', verbose_name='тренировка')),
            ],
            options={
                'verbose_name': 'подход',
                'verbose_name_plural': 'подходы',
                'ordering': ['exercise__name', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='CardioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='дистанция, км')),
                ('avg_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='средний пульс')),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardio', to='workouts.workout', verbose_name='тренировка')),
            ],
            options={
                'verbose_name': 'детали кардио',
                'verbose_name_plural': 'детали кардио',
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_exercise_name_per_owner', violation_error_message='Упражнение с таким названием у вас уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_global_exercise_name', violation_error_message='Глобальное упражнение с таким названием уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='sport',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_sport_name_per_owner', violation_error_message='Вид спорта с таким названием у вас уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='sport',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_global_sport_name', violation_error_message='Глобальный вид спорта с таким названием уже есть.'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', '-started_at'], name='workout_user_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise', 'set_number'), name='unique_set_number_per_exercise', violation_error_message='Подход с таким номером для этого упражнения уже есть.'),
        ),
    ]
