# Generated by Django 6.1 on 2026-08-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
    ]
