# Generated by Django 6.1 on 2026-08-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthset',
            name='done',
            field=models.BooleanField(default=False, verbose_name='выполнен'),
        ),
        migrations.AddField(
            model_name='workout',
            name='current_exercise',
            field=models.ForeignKey(blank=True, help_text='Выбранное вручную упражнение живого режима.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workouts.exercise', verbose_name='текущее упражнение'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — тренировка ещё идёт.', null=True, verbose_name='длительность, мин'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('duration_min__isnull', True)), fields=('user',), name='unique_active_workout_per_user', violation_error_message='У вас уже есть незавершённая тренировка.'),
        ),
    ]
