# Generated by Django 6.1 on 2026-08-27 18:56

from django.db import migrations


def mark_existing_sets_done(apps, schema_editor):
    # До живого режима подход попадал в БД только как уже выполненный.
    # Инвариант «в завершённой тренировке остаются только выполненные подходы»
    # должен выполняться и для старых данных.
    apps.get_model("workouts", "StrengthSet").objects.update(done=True)


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0003_live_mode_fields"),
    ]

    operations = [
        migrations.RunPython(mark_existing_sets_done, migrations.RunPython.noop),
    ]
