# Generated by Django 6.1 on 2026-08-28 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_backfill_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('feature', 'Новое'), ('fix', 'Исправлено')], default='feature', max_length=10, verbose_name='тип')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Можно поставить будущую — запись появится сама. Дата задним числом ниже последнего открытия «Что нового» точку-бейдж не зажжёт.', verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Снято — черновик, в приложении не виден.', verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
