# Generated by Django 6.1 on 2026-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_changelog_entry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='strengthset',
            index=models.Index(fields=['exercise', 'workout'], name='set_exercise_workout_idx'),
        ),
    ]
