# Generated by Django 6.1 on 2026-08-30 19:23
#
# Третье состояние тренировки: черновик (started_at IS NULL) — подготовлена, но не
# начата. Данные не трогаем: у всех существующих строк started_at заполнен, поэтому
# check-констрейнт проходит сразу, а RunPython не нужен.
#
# Откат (migrate workouts 0006) при существующих черновиках УПАДЁТ на возврате
# NOT NULL — и это правильно. Единственный корректный путь назад:
# DELETE FROM workouts_workout WHERE started_at IS NULL;  (плановые подходы уйдут
# каскадом), и только потом migrate 0006. Подставлять черновикам время начала
# нельзя: это создаст тренировки, которых не было, и они попадут в историю,
# агрегаты и рекорды.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_set_exercise_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': [models.OrderBy(models.F('started_at'), descending=True, nulls_last=True), '-id'], 'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
        migrations.RemoveConstraint(
            model_name='workout',
            name='unique_active_workout_per_user',
        ),
        migrations.AlterField(
            model_name='workout',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — тренировка подготовлена, но ещё не начата.', null=True, verbose_name='начало'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('duration_min__isnull', True), ('started_at__isnull', False)), fields=('user',), name='unique_live_workout_per_user', violation_error_message='У вас уже есть незавершённая тренировка.'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', False), ('duration_min__isnull', True), _connector='OR'), name='finished_workout_is_started', violation_error_message='Завершённая тренировка не может быть без начала.'),
        ),
    ]
