# Generated by Django 6.1 on 2026-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_announce_planned_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='measurement',
            field=models.CharField(choices=[('weight_reps', 'Вес × повторы'), ('reps', 'Повторы'), ('time', 'Время'), ('time_weight', 'Время + вес')], default='weight_reps', help_text='Килограммы с повторами, только повторы или время удержания.', max_length=12, verbose_name='измерение'),
        ),
        migrations.AddField(
            model_name='strengthset',
            name='duration_sec',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='время, сек'),
        ),
        migrations.AddField(
            model_name='strengthset',
            name='measurement',
            field=models.CharField(choices=[('weight_reps', 'Вес × повторы'), ('reps', 'Повторы'), ('time', 'Время'), ('time_weight', 'Время + вес')], default='weight_reps', max_length=12, verbose_name='измерение'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_sec', 0), ('measurement', 'weight_reps')), models.Q(('duration_sec', 0), ('measurement', 'reps'), ('weight_kg', 0)), models.Q(('measurement', 'time'), ('reps', 0), ('weight_kg', 0)), models.Q(('measurement', 'time_weight'), ('reps', 0)), _connector='OR'), name='set_fields_match_measurement', violation_error_message='Значения подхода не совпадают с единицей упражнения.'),
        ),
    ]
