# Generated by Django 6.1 on 2026-08-31 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_announce_exercise_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='заметка')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workouts.exercise', verbose_name='упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_notes', to='workouts.workout', verbose_name='тренировка')),
            ],
            options={
                'verbose_name': 'заметка к упражнению',
                'verbose_name_plural': 'заметки к упражнениям',
                'constraints': [models.UniqueConstraint(fields=('workout', 'exercise'), name='unique_note_per_workout_exercise', violation_error_message='Заметка к этому упражнению в тренировке уже есть.')],
            },
        ),
    ]
