# Generated by Django 6.1 on 2026-08-31 11:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_announce_manual_input'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_step', models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='На столько меняют вес кнопки «−» и «+» в живом режиме.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('50'))], verbose_name='шаг веса, кг')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='workouts.exercise', verbose_name='упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_settings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'настройки упражнения',
                'verbose_name_plural': 'настройки упражнений',
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='unique_settings_per_user_exercise', violation_error_message='Настройки этого упражнения у вас уже есть.')],
            },
        ),
    ]
