# Generated by Django 6.1 on 2026-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_announce_weight_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthset',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='выполнен в'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.CheckConstraint(condition=models.Q(('done', True), ('done_at__isnull', True), _connector='OR'), name='set_done_at_only_when_done', violation_error_message='Время выполнения бывает только у выполненного подхода.'),
        ),
    ]
