# Generated by Django 6.1 on 2026-09-02 17:50
#
# Справочник мест тренировок: зал, дом, маршрут — одна сущность на всё.
#
# Место по умолчанию держит частичный уникальный индекс
# (unique_default_location_per_owner), а не FK в accounts: у User нет ни одного
# FK, и ссылка на workouts.Location завела бы обратную зависимость приложений.
# Цена решения: менять дефолт надо ДВУМЯ UPDATE'ами («снять у всех», потом
# «поставить одному») внутри select_for_update. Одним оператором нельзя —
# частичный UniqueConstraint в Postgres это UNIQUE INDEX, он проверяется
# немедленно и построчно, а deferrable вместе с condition Django запрещает.
#
# Workout.location — nullable + PROTECT. NULL означает «место не указано»: так
# записана вся существующая история, и бэкфилл невозможен (данных «где
# тренировался» не существует ни в каком виде) и вреден — он был бы выдумкой.
# PROTECT, как у sport: удаление использованного места объясняет готовый
# CatalogDeleteView, а вместо удаления есть переименование.
#
# Откат (migrate workouts 0020) пройдёт без ошибок, но УНИЧТОЖИТ данные:
# колонку location_id и всю таблицу мест. Восстановления нет.

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_announce_trained_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Зал, дом или маршрут: «СпортЛайф», «Дома», «Парк у реки».', max_length=80, verbose_name='название')),
                ('is_default', models.BooleanField(default=False, help_text='Такое место одно: его молча получает новая силовая тренировка.', verbose_name='по умолчанию')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Пусто — место не указано.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='workouts.location', verbose_name='место'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_location_name_per_owner', violation_error_message='Место с таким названием у вас уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='unique_default_location_per_owner', violation_error_message='Место по умолчанию может быть только одно.'),
        ),
    ]
