# Generated by Django 6.1 — цель по времени и плановый день у подготовленной тренировки.
#
# Оба поля новые и nullable, существующим строкам ничего не делаем: у всех NULL,
# и констрейнт проходит сразу.
#
# Почему отдельные колонки, хотя цель по дистанции лежит в поле факта
# (CardioDetails.distance_km): distance_km — это только данные, а duration_min и
# started_at ещё и задают состояние тренировки. Цель в duration_min строка бы даже
# не приняла — finished_workout_is_started отвергает duration_min NOT NULL при
# пустом started_at; плановый день в started_at сделал бы черновик «идущим», и
# второй такой упёрся бы в unique_live_workout_per_user.
#
# Откат (migrate workouts 0025) безопасен и обратим — проверено в обе стороны:
# снимается констрейнт и удаляются две колонки, ни одна существующая проверка на
# них не опирается. Потеряются только цели неначатых черновиков.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_announce_cardio_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='planned_for',
            field=models.DateField(blank=True, help_text='Только у черновика: день, на который тренировка подготовлена.', null=True, verbose_name='на какой день'),
        ),
        migrations.AddField(
            model_name='workout',
            name='target_duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Только у подготовленной тренировки.', null=True, verbose_name='цель по времени, мин'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('planned_for__isnull', True), _connector='OR'), name='planned_for_only_when_planned', violation_error_message='Плановый день бывает только у черновика.'),
        ),
    ]
