# Generated by Django 6.1 on 2026-10-03 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0043_announce_exercise_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_changelog_entries', to=settings.AUTH_USER_MODEL, verbose_name='прочитали'),
        ),
    ]
