# Generated by Django 6.1 on 2026-10-03 17:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0047_announce_workout_correct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('unit', models.CharField(blank=True, help_text='Подпись к числу: «кг», «см», «%». Пусто — число без подписи.', max_length=12, verbose_name='единица')),
                ('owner', models.ForeignKey(blank=True, help_text='Пусто — глобальная запись, видна всем пользователям.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'параметр тела',
                'verbose_name_plural': 'параметры тела',
                'ordering': [models.OrderBy(models.F('owner'), nulls_first=True), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='значение')),
                ('measured_on', models.DateField(verbose_name='день замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='workouts.bodymetric', verbose_name='параметр')),
            ],
            options={
                'verbose_name': 'замер',
                'verbose_name_plural': 'замеры',
                'ordering': ['-measured_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bodymetric',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_body_metric_name_per_owner', violation_error_message='Параметр с таким названием у вас уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='bodymetric',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_global_body_metric_name', violation_error_message='Общий параметр с таким названием уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='bodymeasurement',
            constraint=models.UniqueConstraint(fields=('user', 'metric', 'measured_on'), name='unique_body_measurement_per_day'),
        ),
        migrations.AddConstraint(
            model_name='bodymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='body_measurement_value_positive'),
        ),
    ]
