# Generated by Django 6.1 on 2026-10-04 18:41

import django.db.models.deletion
import django.utils.timezone
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0054_announce_live_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='удалена')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='подзаголовок')),
                ('color_key', models.CharField(blank=True, max_length=32, verbose_name='цвет вида спорта')),
                ('payload', models.JSONField(encoder=workouts.models.ExactJSONEncoder, verbose_name='снимок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_workouts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'удалённая тренировка',
                'verbose_name_plural': 'удалённые тренировки',
                'ordering': ['-deleted_at', '-id'],
                'indexes': [models.Index(fields=['user', '-deleted_at'], name='deleted_workout_user_idx')],
            },
        ),
    ]
