# Generated by Django 6.1 on 2026-10-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0057_announce_account_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthset',
            name='circuit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='круг'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.CheckConstraint(condition=models.Q(('circuit__isnull', True), ('circuit__gte', 1), _connector='OR'), name='set_circuit_is_positive', violation_error_message='Номер круга начинается с единицы.'),
        ),
    ]
