# Generated by Django 6.1 on 2026-10-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0067_announce_feedback_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=60, verbose_name='производитель')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='модель')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='workouts.exercise', verbose_name='упражнение')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='workouts.location', verbose_name='место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_machines', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'тренажёр',
                'verbose_name_plural': 'тренажёры',
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise', 'location'), name='unique_machine_per_exercise_location'), models.CheckConstraint(condition=models.Q(('brand', ''), ('model', ''), _negated=True), name='machine_is_not_empty')],
            },
        ),
    ]
