# Generated by Django 6.1 on 2026-10-10 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0074_announce_machine_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='contributed_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, чья заявка добавила запись в общий справочник.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='machinebrand',
            name='contributed_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, чья заявка добавила запись в общий справочник.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='contributed_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, чья заявка добавила запись в общий справочник.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
