# Generated by Django 6.1 on 2026-10-10 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0075_catalog_contributed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exercise', 'Упражнение'), ('brand', 'Производитель'), ('model', 'Модель тренажёра')], max_length=10, verbose_name='что')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='комментарий автора')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='статус')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='причина отказа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='отправлена')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='рассмотрена')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workouts.machinebrand')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workouts.exercise')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='workouts.machinemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'заявка в общий справочник',
                'verbose_name_plural': 'заявки в общий справочник',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('exercise__isnull', False), ('kind', 'exercise'), ('model__isnull', True)), models.Q(('brand__isnull', False), ('exercise__isnull', True), ('kind', 'brand'), ('model__isnull', True)), models.Q(('brand__isnull', True), ('exercise__isnull', True), ('kind', 'model'), ('model__isnull', False)), _connector='OR'), name='catalog_request_item_matches_kind'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='rejected_request_has_reason', violation_error_message='Укажите причину отказа.'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('exercise',), name='unique_pending_exercise_request', violation_error_message='Заявка уже на рассмотрении.'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('brand',), name='unique_pending_brand_request', violation_error_message='Заявка уже на рассмотрении.'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('model',), name='unique_pending_model_request', violation_error_message='Заявка уже на рассмотрении.')],
            },
        ),
    ]
